### ISSUE TITLE
Uncaught Error:  Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by phoenisx** [xojs/vscode-linter-xo#147]
## Desctription

Hi I am getting an uncaught error whenever I open a TS file. In DevTools I see the following error stack trace, maybe it might help

```
mainThreadExtensionService.ts:78 [samverschueren.linter-xo]Illegal argument: line must be non-negative
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
mainThreadExtensionService.ts:79 Error: Illegal argument: line must be non-negative
	at ke (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:1186)
	at new io (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:20809)
	at new ys (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:22363)
	at y (~/.vscode/extensions/samverschueren.linter-xo-3.20.0/dist/client.js:35:65074)
	at l (~/.vscode/extensions/samverschueren.linter-xo-3.20.0/dist/client.js:35:64052)
	at s (~/.vscode/extensions/samverschueren.linter-xo-3.20.0/dist/client.js:35:46652)
	at Object.dR [as map] (~/.vscode/extensions/samverschueren.linter-xo-3.20.0/dist/client.js:35:46738)
	at Object.a [as asDiagnostics] (~/.vscode/extensions/samverschueren.linter-xo-3.20.0/dist/client.js:35:63906)
	at yh.workDiagnosticQueue (~/.vscode/extensions/samverschueren.linter-xo-3.20.0/dist/client.js:41:11624)
	at Immediate.<anonymous> (~/.vscode/extensions/samverschueren.linter-xo-3.20.0/dist/client.js:41:11296)
	at process.processImmediate (node:internal/timers:483:21)
```
![image](https://github.com/user-attachments/assets/c042c034-7fb4-4dbf-b280-3fe6a5a18da0)

I am not sure what exactly the reason is. The following are my details:

- Ubuntu
- VSCode v1.95.2

Following is my content from `.xo-config.js`
```js
module.exports = {
	"extends": [
		"xo-react"
	]
}
```

I tried changing the above config filename to `.xo-config.json` but it didn't work either.

**Comment by spence-s** [comment]
This should be solved when moving to latest versions of `xo` - I don't have any plans to try to correct bugs in older versions.
