### ISSUE TITLE
Distinct(?) 'TypeError: Path must be a string. Received null'

### ISSUE THREAD

**Issue by idmyn** [xojs/vscode-linter-xo#51]
I've just installed VS Code (macOS) and this extension but received an error upon editing a JavaScript file. I'm not sure if it's distinct from issue #49 - forgive me if I'm missing something. I've tried uninstalling all other extensions to no avail. Any ideas how I could fix this?

Error message pasted below. The TypeError is repeated five times and followed by a notification that the server will not be restarted.

```
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Package.isDependency (/Users/david/.vscode/extensions/samverschueren.linter-xo-2.2.2/server/out/package.js:11:48)
    at Linter.validate (/Users/david/.vscode/extensions/samverschueren.linter-xo-2.2.2/server/out/server.js:122:27)
    at Linter.validateSingle (/Users/david/.vscode/extensions/samverschueren.linter-xo-2.2.2/server/out/server.js:114:21)
    at Object.Linter.messageQueue.onNotification.document [as handler] (/Users/david/.vscode/extensions/samverschueren.linter-xo-2.2.2/server/out/server.js:23:18)
    at BufferedMessageQueue.processQueue (/Users/david/.vscode/extensions/samverschueren.linter-xo-2.2.2/server/out/bufferedMessageQueue.js:117:18)
    at Immediate.timer.setImmediate (/Users/david/.vscode/extensions/samverschueren.linter-xo-2.2.2/server/out/bufferedMessageQueue.js:80:18)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
[Info  - 08:07:33] Connection to server got closed. Server will restart.
/Users/david/.vscode/extensions/samverschueren.linter-xo-2.2.2/server/out/package.js:20
            throw err;
            ^
```

_The XO Linter server crashed 5 times in the last 3 minutes. The server will not be restarted._

**Comment by yakov116** [comment]
@idmyn are you still having an issue?

**Comment by idmyn** [comment]
Haven't used this extension in years so not sure if the issue is fixed but I'm happy to close
